### PR TITLE
Add support for SHA256-Digest.

### LINKED ISSUE #20: Add support for SHA256-Digest
Manifest and signature files currently use MD5-Digest and SHA1-Digest. Support of SHA256-Digest should also be added.

```
Signature-Version: 1.0
MD5-Digest-Manifest: 7wtE51vmm46VPFa/6At5fw==
SHA1-Digest-Manifest: FLdAHdt/V7ETz3+BLQKGpQAzz2E=
SHA256-Digest-Manifest: r/E2S8/q69YKONE++lwI+JxnPbVU13X3juxyLzEPC/M=
```

### PR DESCRIPTION
**Pull request by EnTeQuAk**
Fixes #20

r? @jvehent 

One question on this, do we need to care about backwards compatibility in any way? Like, generate different manifest files for different firefox versions or something? I don't think we do but I'm just curious.

### CODE REVIEW

**Comment by jvehent** [comment]
r+, but I think we'll need QA testing to make sure the manifest still works in Firefox. @dveditz might know.

We care about backward compatibility. I don't think we've ever used MD5, but SHA1 is definitely in use today, and current versions of Fx rely on it.

**Comment by EnTeQuAk** [comment]
> We care about backward compatibility. I don't think we've ever used MD5, but SHA1 is definitely in use today, and current versions of Fx rely on it.

Yeah, I wasn't going to deprecate / remove any features.

> but I think we'll need QA testing to make sure the manifest still works in Firefox.

Answers that question I think, looking forward to any feedback!

**Comment by EnTeQuAk** [comment]
> r+, but I think we'll need QA testing to make sure the manifest still works in Firefox. @dveditz might know.

@jvehent any news on this or a bug in bugzilla that I can track?

**Comment by jvehent** [comment]
If you have a branch that works, we can try signing a couple addons with the staging key, and give that to AMO QA. I think that's the right next step.

**Comment by EnTeQuAk** [comment]
> If you have a branch that works, we can try signing a couple addons with the staging key, and give that to AMO QA. I think that's the right next step.

Sounds like a perfect plan. I'll do that an follow up early next week (currently at a conference so only limited time to work on this).

**Comment by EnTeQuAk** [comment]
Merged, I'll release it once https://github.com/mozilla/addons-server/pull/7095 lands.

**Pull request merged**
